{"name": "test_for_users_duplicate", "status": "failed", "statusDetails": {"message": "AssertionError: Response does not have expected fields: ['data1']", "trace": "@allure.feature(\"Create already exist User\")\n    @allure.story(\"Authorized user can not add users information\")\n    @allure.severity(allure.severity_level.BLOCKER)\n    def test_for_users_duplicate():\n    \n        response = helper.post_request(url=POST_URL,\n                                              body={'name':'Abhishek Yadav', 'gender':'Male',\n                                                    'email':'yabhishek@outlook.com', 'status':'Active'})\n    \n        check.response_has_status_code(response, 200)\n        check.response_has_field_with_value(response, 'code', 422)\n        check.response_has_fields(\n            response,\n>           'data1'\n        )\n\nresponse   = <Response [200]>\n\ntest.py:66: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse = <Response [200]>, fields = ('data1',), missing_fields = ['data1']\n\n    def response_has_fields(response, *fields):\n        with allure.step(f'Check response jsondata have all of {fields} fields'):\n            jsondata = response.json()\n            missing_fields = [field for field in fields if jsondata.get(field) is None]\n>           assert not missing_fields, f'Response does not have expected fields: {missing_fields}'\nE           AssertionError: Response does not have expected fields: ['data1']\n\nfields     = ('data1',)\njsondata   = {'code': 422,\n 'data': [{'field': 'email', 'message': 'has already been taken'}],\n 'meta': None}\nmissing_fields = ['data1']\nresponse   = <Response [200]>\n\n..\\testlib\\check.py:51: AssertionError"}, "steps": [{"name": "Send POST request by authorized user to url:\n https://gorest.co.in/public-api/users", "status": "passed", "attachments": [{"source": "d120fe3f-d9a9-4615-9a20-be88198fe495-attachment.attach"}, {"source": "8bd62cca-ff4b-4489-a792-b5f97dd4b1f6-attachment.attach"}], "start": 1620599875901, "stop": 1620599876326}, {"name": "Check response has one of (200,) status code", "status": "passed", "start": 1620599876326, "stop": 1620599876326}, {"name": "Check response jsondata have code field with 422 value", "status": "passed", "start": 1620599876326, "stop": 1620599876326}, {"name": "Check response jsondata have all of ('data1',) fields", "status": "failed", "statusDetails": {"message": "AssertionError: Response does not have expected fields: ['data1']\n", "trace": "  File \"D:\\MyWorkspace\\api_tests_python_allure\\testlib\\check.py\", line 51, in response_has_fields\n    assert not missing_fields, f'Response does not have expected fields: {missing_fields}'\n"}, "start": 1620599876327, "stop": 1620599876327}], "start": 1620599875901, "stop": 1620599876329, "uuid": "baa4941c-89e2-4ccc-9213-48273d5e4776", "historyId": "90db21108ff4a0e23ca7eeedefc30d6d", "testCaseId": "2b61faf00e535626e31545461e44eb04", "fullName": "tests.test#test_for_users_duplicate", "labels": [{"name": "feature", "value": "Create already exist User"}, {"name": "story", "value": "Authorized user can not add users information"}, {"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test"}, {"name": "host", "value": "abhishekkyd"}, {"name": "thread", "value": "9512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test"}]}