{"name": "test_for_users_duplicate", "status": "failed", "statusDetails": {"message": "AssertionError: \n            Expected 'code' field value don't equal to:\n            422\n            Actual 'code' field value:\n            201", "trace": "@allure.feature(\"Create already exist User\")\n    @allure.story(\"Authorized user can not add users information\")\n    @allure.severity(allure.severity_level.BLOCKER)\n    def test_for_users_duplicate():\n    \n        response = helper.post_request(url=POST_URL,\n                                              body={'name':'Abhishek Yadav', 'gender':'Male',\n                                                    'email':'yabhishek@outlook.com', 'status':'Active'})\n    \n        check.response_has_status_code(response, 200)\n>       check.response_has_field_with_value(response, 'code', 422)\n\nresponse   = <Response [200]>\n\ntest.py:63: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse = <Response [200]>, field = 'code', value = 422\n\n    def response_has_field_with_value(response, field, value):\n        with allure.step(f'Check response jsondata have {field} field with {value} value'):\n            actual_field_value = response.json().get(field)\n            assert actual_field_value, f'Response does not have expected {field} field'\n            assert value == actual_field_value, f'''\n                Expected '{field}' field value don't equal to:\n                {value}\n                Actual '{field}' field value:\n                {actual_field_value}\n>           '''\nE           AssertionError: \nE                       Expected 'code' field value don't equal to:\nE                       422\nE                       Actual 'code' field value:\nE                       201\n\nactual_field_value = 201\nfield      = 'code'\nresponse   = <Response [200]>\nvalue      = 422\n\n..\\testlib\\check.py:72: AssertionError"}, "steps": [{"name": "Send POST request by authorized user to url:\n https://gorest.co.in/public-api/users", "status": "passed", "attachments": [{"source": "ab2bfed9-a3bc-4452-8fc5-124ab29f1114-attachment.attach"}, {"source": "404fae14-97dc-4657-aad9-b65e5d48668d-attachment.attach"}], "start": 1620599857269, "stop": 1620599857702}, {"name": "Check response has one of (200,) status code", "status": "passed", "start": 1620599857703, "stop": 1620599857703}, {"name": "Check response jsondata have code field with 422 value", "status": "failed", "statusDetails": {"message": "AssertionError: \n            Expected 'code' field value don't equal to:\n            422\n            Actual 'code' field value:\n            201\n        \n", "trace": "  File \"D:\\MyWorkspace\\api_tests_python_allure\\testlib\\check.py\", line 72, in response_has_field_with_value\n    '''\n"}, "start": 1620599857703, "stop": 1620599857703}], "start": 1620599857269, "stop": 1620599857705, "uuid": "44f82429-a26b-45b2-bb88-b02342cc5507", "historyId": "90db21108ff4a0e23ca7eeedefc30d6d", "testCaseId": "2b61faf00e535626e31545461e44eb04", "fullName": "tests.test#test_for_users_duplicate", "labels": [{"name": "severity", "value": "blocker"}, {"name": "feature", "value": "Create already exist User"}, {"name": "story", "value": "Authorized user can not add users information"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test"}, {"name": "host", "value": "abhishekkyd"}, {"name": "thread", "value": "10924-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test"}]}